name: Build

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:win
        env:
          VITE_BRM_API_URL: ${{ secrets.BRM_API_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: windows-installer
          path: dist/*.exe

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm ci
      - run: npm run build:mac
        env:
          VITE_BRM_API_URL: ${{ secrets.BRM_API_URL }}
      - uses: actions/upload-artifact@v4
        with:
          name: mac-dmg
          path: dist/*.dmg
